[package]
name = "byten"
version = "0.1.0"
edition = "2024"

[features]
default = ["derive"]
derive = ["dep:byten_derive"]

[dependencies]
byten_derive = { path = "../byten_derive", optional = true }
heapless = "0.9.1"
