[package]
name = "binary_codec"
version = "0.1.0"
edition = "2024"

[features]
default = ["derive"]
derive = ["dep:binary_codec_derive"]

[dependencies]
binary_codec_derive = { path = "../binary_codec_derive", optional = true }
